<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Architecture.Analyzer\Architecture.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\rgpd\HR.Module\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\rgpd\HR.Module\.editorconfig" />
  </ItemGroup>

</Project>
