//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Architecture.Analyzer {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Architecture.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans &apos;{0}&apos;, la propriété &apos;{1}&apos; doit être placée avant &apos;{2}&apos; car les propriétés doivent être ordonnées alphabétiquement hors identifiants..
        /// </summary>
        internal static string ClassPropertyOrderMessageFormat {
            get {
                return ResourceManager.GetString("ClassPropertyOrderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les propriétés du DTO ne sont pas ordonnées.
        /// </summary>
        internal static string ClassPropertyOrderTitle {
            get {
                return ResourceManager.GetString("ClassPropertyOrderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans &apos;{0}&apos;, la méthode &apos;{1}&apos; doit être placée avant &apos;{2}&apos; car les méthodes doivent être ordonnées alphabétiquement..
        /// </summary>
        internal static string ClassMethodOrderMessageFormat {
            get {
                return ResourceManager.GetString("ClassMethodOrderMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les méthodes de la classe ne sont pas ordonnées.
        /// </summary>
        internal static string ClassMethodOrderTitle {
            get {
                return ResourceManager.GetString("ClassMethodOrderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; ne doit pas implémenter l&apos;interface provider &apos;{1}&apos; dans le module &apos;{2}&apos;..
        /// </summary>
        internal static string LocalProviderImplementationMessageFormat {
            get {
                return ResourceManager.GetString("LocalProviderImplementationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Implémentation provider interdite dans le module.
        /// </summary>
        internal static string LocalProviderImplementationTitle {
            get {
                return ResourceManager.GetString("LocalProviderImplementationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La classe &apos;{0}&apos; ajoute {1} lignes de code et dépasse le budget de {2} lignes..
        /// </summary>
        internal static string LocBudgetClassMessageFormat {
            get {
                return ResourceManager.GetString("LocBudgetClassMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La classe dépasse le budget de lignes ajoutées par le prompt.
        /// </summary>
        internal static string LocBudgetClassTitle {
            get {
                return ResourceManager.GetString("LocBudgetClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La méthode &apos;{0}&apos; ajoute {1} lignes de code et dépasse le budget de {2} lignes..
        /// </summary>
        internal static string LocBudgetMethodMessageFormat {
            get {
                return ResourceManager.GetString("LocBudgetMethodMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La méthode dépasse le budget de lignes ajoutées par le prompt.
        /// </summary>
        internal static string LocBudgetMethodTitle {
            get {
                return ResourceManager.GetString("LocBudgetMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet &apos;{0}&apos; ajoute {1} lignes de code et dépasse le budget de {2} lignes..
        /// </summary>
        internal static string LocBudgetProjectMessageFormat {
            get {
                return ResourceManager.GetString("LocBudgetProjectMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet dépasse le budget de lignes ajoutées par le prompt.
        /// </summary>
        internal static string LocBudgetProjectTitle {
            get {
                return ResourceManager.GetString("LocBudgetProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La solution &apos;{0}&apos; ajoute {1} lignes de code et dépasse le budget global de {2} lignes..
        /// </summary>
        internal static string LocBudgetSolutionMessageFormat {
            get {
                return ResourceManager.GetString("LocBudgetSolutionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La solution dépasse le budget global de lignes ajoutées par le prompt.
        /// </summary>
        internal static string LocBudgetSolutionTitle {
            get {
                return ResourceManager.GetString("LocBudgetSolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le module &apos;{0}&apos; doit contenir le dossier &apos;Models/Data/Providers&apos; avec au moins une interface..
        /// </summary>
        internal static string MissingProviderContractsMessageFormat {
            get {
                return ResourceManager.GetString("MissingProviderContractsMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contrats providers manquants dans un module.
        /// </summary>
        internal static string MissingProviderContractsTitle {
            get {
                return ResourceManager.GetString("MissingProviderContractsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; se termine par &apos;{1}&apos; et doit être dans le dossier &apos;{2}&apos;..
        /// </summary>
        internal static string ModelDirectoryMessageFormat {
            get {
                return ResourceManager.GetString("ModelDirectoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de modèle dans le mauvais dossier.
        /// </summary>
        internal static string ModelDirectoryTitle {
            get {
                return ResourceManager.GetString("ModelDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; doit être déclaré dans un fichier nommé &apos;{1}&apos;..
        /// </summary>
        internal static string ModelFileNameMessageFormat {
            get {
                return ResourceManager.GetString("ModelFileNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du fichier doit correspondre au nom du type.
        /// </summary>
        internal static string ModelFileNameTitle {
            get {
                return ResourceManager.GetString("ModelFileNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le type &apos;{0}&apos; n&apos;est pas autorisé dans le dossier &apos;{1}&apos;. Suffixes autorisés : &apos;{2}&apos;..
        /// </summary>
        internal static string ModelFolderAllowedMessageFormat {
            get {
                return ResourceManager.GetString("ModelFolderAllowedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de modèle dans un dossier non autorisé.
        /// </summary>
        internal static string ModelFolderAllowedTitle {
            get {
                return ResourceManager.GetString("ModelFolderAllowedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier requis manquant dans le projet.
        /// </summary>
        internal static string RequiredProjectFolderTitle {
            get {
                return ResourceManager.GetString("RequiredProjectFolderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet &apos;{0}&apos; doit contenir le dossier &apos;{1}&apos; avec au moins un fichier..
        /// </summary>
        internal static string RequiredProjectFolderMessageFormat {
            get {
                return ResourceManager.GetString("RequiredProjectFolderMessageFormat", resourceCulture);
            }
        }

        internal static string ModuleReferenceBarrierTitle {
            get {
                return ResourceManager.GetString("ModuleReferenceBarrierTitle", resourceCulture);
            }
        }

        internal static string ModuleReferenceBarrierMessageFormat {
            get {
                return ResourceManager.GetString("ModuleReferenceBarrierMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de la variable est trop court.
        /// </summary>
        internal static string NameLengthVariableTitle {
            get {
                return ResourceManager.GetString("NameLengthVariableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à La variable &apos;{0}&apos; a un nom de {1} caractère(s) et doit en comporter au moins {2}..
        /// </summary>
        internal static string NameLengthVariableMessageFormat {
            get {
                return ResourceManager.GetString("NameLengthVariableMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de la classe est trop court.
        /// </summary>
        internal static string NameLengthClassTitle {
            get {
                return ResourceManager.GetString("NameLengthClassTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à La classe &apos;{0}&apos; a un nom de {1} caractère(s) et doit en comporter au moins {2}..
        /// </summary>
        internal static string NameLengthClassMessageFormat {
            get {
                return ResourceManager.GetString("NameLengthClassMessageFormat", resourceCulture);
            }
        }
    }
}
